### ISSUE TITLE
What's `encrypted` array for?

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#100]
I'm studying the private index trying to understand it and how to speed up the code, I noticed there are two indexes `encrypted` and `canDecrypt`.

`encrypted` is all messages that are boxed, `canDecrypt` is a subset of `encrypted` which are those messages hops0 author can successfully unbox.

However, `encrypted` is saved and loaded but other than that it's not *used* anywhere. I mean, nothing *reads* it, it's only written. So why do we have it?

@arj03

**Comment by arj03** [comment]
It will be needed for box2, so we can only try to decrypt those instead of all messages in the log.

**Comment by staltz** [comment]
Thanks, I think this answers my question. :)
