### ISSUE TITLE
db.get() should return full msg

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#119]
when db.get() succeeds, it calls the cb with `results[0].value`. I would need this to return msg so that it has both `msg.key` and `msg.value`, not `msgValue`.

**Comment by mixmix** [comment]
Are you gonna stick to the api of ssb-db?
Ie Takes :
- msgId
- int
- object { meta, private }

**Comment by mixmix** [comment]
Oh sorry that's ssb.get

**Comment by arj03** [comment]
@staltz where in the code of manyverse do you need this functionality? By default get in ssb-db returns the value. I was trying to mimic that api. I don't like overloading methods like it was done it ssb-db where you can as mix say have 3 different kinds of input. I'd rather a new method if you need to get the key as well.

I did notice that if you do a get for something that is not in the database that you will just get (undefined, undefined) back which is not nice. I think get in ssb.db returns on error in that case.

**Comment by staltz** [comment]
I use it like this https://github.com/ssbc/ssb-threads/blob/1afa83380449b7df04ef16b98246574eb3e8fc7e/index.ts#L440

**Comment by staltz** [comment]
I could just put the `key` together with the returned `value`, but this would be missing the `timestamp`, so I think we still need to find a way of supporting this in db2. I'm thinking why is the default of `db.get` to return the value? Isn't it more likely to cover all the use cases if you provide all the data about the msg? Simply because it has all the data about the msg.

**Comment by arj03** [comment]
I was thinking of adding a getMessage that would return the whole thing. If I remember correct get is used in other places as well, like EBT so would be good that it was behaving the same as before.

**Comment by staltz** [comment]
getMessage works for me, but getMsg would be even better 😋 (I like to call SSB messages "msgs" consistently to distinguish from the more generic meaning of the word message)

**Comment by staltz** [comment]
> If I remember correct get is used in other places as well, like EBT so would be good that it was behaving the same as before.

Is this the case? I didn't find it. I think anywhere where we use `db.get(id, cb)` we could just do `db.get(id, (err, msg) => err ?  cb(err) : cb(err, msg.value))`

**Comment by arj03** [comment]
I think it best to let get behave like it did in ssb-db and add the new method.

**Comment by staltz** [comment]
Okay, I'm satisfied with getMsg, I was just trying to challenge why do we strictly need the previous behavior. We're anyway doing a rewrite of ssb-db so now is the moment to ask "do we need this?" for lots of things.

**Comment by mixmix** [comment]
Remember get sometimes takes an integer (offset). I think that might have
beef used by some views, but would have to look
