### ISSUE TITLE
canDecrypt index seems empty

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#124]
![Screenshot_20210116-182447_1.png](https://user-images.githubusercontent.com/90512/104817186-4ab14600-5828-11eb-8838-c6d5eca7cc42.png)

From my Manyverse. I am making queries for private messages and they seem stuck. I'm gonna delete this canDecrypt file and restart the app.

**Comment by staltz** [comment]
Deleted, and it got recreated again with just 4 bytes, which are: `fa3c fe2c`

**Comment by staltz** [comment]
Now I deleted both `canDecrypt.index` and `encrypted.index`. They get "rebuilt", but `canDecrypt.index` stays stuck at 4 bytes and `encrypted.index` stays stuck at 178 bytes.

**Comment by arj03** [comment]
This is without any normal indexes right? Only jitdb queries. It should still work, private messages are working for me in the browser.

**Comment by staltz** [comment]
What do you mean with normal indexes? ssb-db flume indexes or ssb-db2 base index etc? I think both of these are used in Manyverse right now.

**Comment by arj03** [comment]
I was thinking of the db2 base index. This is quite strange.

**Comment by staltz** [comment]
I tried changing `ssb-keys-neon` back to `ssb-keys` and it didn't fix the issue. I'm still clueless what's going on, we could try to pair on this issue again. (PS: in [ssb-threads](https://github.com/ssbc/ssb-threads/pull/6) tests, private index with ssb-db2 also works fine)

**Comment by arj03** [comment]
This is so strange. Lets pair on this tomorrow. I have time during the morning.
