### ISSUE TITLE
Expose operators

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#131]
Should we expose operators in the api so that we can do:

```
const { and, type, live, toPullStream } = ssb.db.operators
```

instead of:

```
const { and, type, live, toPullStream } = require('ssb-db2/operators')
```

This means that we can use the operators without requiring ssb-db2 if it was loaded as a plugin to secret-stack.

**Comment by staltz** [comment]
works for me :)
