### ISSUE TITLE
implicit db2.onDrain inside db2.query()

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#16]
It seems to me that the README example doesn't work as-is, instead requires to be wrapped in `onDrain`. Could we change the end-developer interface so that onDrain is an internal concern and otherwise is always done implicitly?

**Comment by arj03** [comment]
This is related to #8. I think it would be a good idea to add to query as well. I'm not sure it is needed for the other methods as they are mostly internal methods.
