### ISSUE TITLE
Level indexes have different `processed`

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#167]
This shows in Manyverse (Android) when starting up the app. Shouldn't all these `processed` seqs be the same?

```
ssb:db2:base got index status: { version: 1, offset: 767860823, processed: 2365509 }
ssb:db2:ebt got index status: { version: 1, offset: 767860823, processed: 1349552 }
ssb:db2:contacts got index status: { version: 2, offset: 767860823, processed: 1016108 }
ssb:db2:fullMentions got index status: { version: 1, offset: 767860823, processed: 1124452 }
```

**Comment by arj03** [comment]
That is indeed a bit strange. Also why would any of them be 2 365 509. You shouldn't have 2.3 million messages in there?

**Comment by staltz** [comment]
Yeah I definitely don't have 2 mil msgs

**Comment by arj03** [comment]
I'm seeing the same pattern here if I enable db2 debug

**Comment by arj03** [comment]
I think this happens if an index reindexes. So like if you remove an index so one of them is behind the others. So it's pretty harmless. I just means that the index actually was called 2.5 million times, but that the 1 something was just calls it had already indexed. Anyway would be nice to fix.

**Comment by staltz** [comment]
Good to know. And yeah, it's harmless now, but if later we start depending on the `seq` semantics of this counter, than maybe there would be bugs, so good to fix.

**Comment by arj03** [comment]
Yeah, I can have a go at fixing this.
