### ISSUE TITLE
Custom log.stream in bipf

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#170]
I'm thinking about ssb-threads, and it fetches a bunch of msgs before it fetches the one it wants:

1. In descending order, fetch all posts
2. For each post msg, look for the msg.value.content.root field
3. Fetch that root's msg
4. Etc

Currently, for 1, it queries some JIT indexes. This means two heavy things: build the index by scanning the entire log (okay, just once), and fetch the full record (meaning convert bipf to JSON).

I'm thinking that we can do this in a lighter way:

1. Scan the log in bipf (don't convert to JSON) in descending order (note that we won't have to the the entire log scan! We can just scan a couple recent msgs because that's the only thing ssb-threads is interested in. That said, the scan ordering is arrival timestamp, not "min timestamp" unfortunately)
2. Given the bipf buffer, seek the value.content.root with bipf seekers
3. (Same as step num 3 above)
4. Etc

I guess my point is that it would be good to have an API where we descending-scan the bipf log (forget about the ordering problem for now), just looking for a few recent values, and this might be faster than actually building indexes and querying them. 

Thoughts @arj03 ?

**Comment by staltz** [comment]
I quickly tried out this idea and it didn't seem to give any perf improvement :/

It seems like msg-by-msg `bipf.decode` is not heavy at all, maybe the heavy thing is the disk I/O fetch in the first place (in case it's not in cache).

**Comment by arj03** [comment]
Bummer. My initial reactions was that this could be useful while it was indexing on first load. I'm doing the about self index now. Will open a PR for you to review tomorrow.

**Comment by staltz** [comment]
Maybe I should let you know what exactly I tried:

I did it in jitdb, I just added another meta opt `rawFormat` passed to paginate which in turn passes to getMessagesFromBitsetSlice. Then instead of a `getMessage` it does a `getRecord`. So it still does the sorted timestamp part, the only difference is getRecord versus getMessage
