### ISSUE TITLE
Some issues with aboutSelf

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#207]
I'm pretty sure (and @powersource also found some cases) where the user's about is a very old one, definitely not the latest self-assigned, e.g. `andrestaltz` (desktop) below, the profile pic is super old:

![photo_2021-03-02_16-06-22](https://user-images.githubusercontent.com/90512/109660210-425f6100-7b71-11eb-8d50-57de3f298bec.jpg)

**Comment by arj03** [comment]
I can have a go at debugging that if you want?

**Comment by staltz** [comment]
Oh, good! Thanks

**Comment by arj03** [comment]
Just tested on my main log and I get the correct picture. It finished indexing right?

**Comment by Powersource** [comment]
Yep issue persists after several days of using the app

**Comment by staltz** [comment]
> Just tested on my main log and I get the correct picture. It finished indexing right?

I think it finished indexing because I see from logs that db2 loaded such and such plugins, and all of them including aboutSelf have the same offset and processed number.

**Comment by staltz** [comment]
I'll try to reproduce on my desktop.

**Comment by staltz** [comment]
Can't reproduce on desktop, I'm now trying on mobile to turn off the "cachedAboutSelf" plugin, let's see what that does.

Nope, didn't make a difference.

Let's see if deleting `aboutSelf` and letting it rebuild helps.

Nope, still giving old abouts. This is mysterious...

**Comment by arj03** [comment]
At least it is reproducible on mobile ;-)

**Comment by arj03** [comment]
I ran this to make sure that I had all the about messages, maybe that tells you something:

```
sbot.db.query(
  and(
   type('about'),
   author('@QlCTpvY7p9ty2yOFrv1WU1AE88aoQc4Y7wYal7PFc+w=.ed25519')
  ),
  descending(),
  toCallback((err, msgs) => {
    console.log(msgs.filter(m => m.value.content.about == m.value.author).map(m => m.value.content))
    sbot.close()
  })
)
```

**Comment by staltz** [comment]
I put custom logs in and it seems that the abouts are all correctly there, they just come in the wrong order which means that one of the older ones is the last one to call `updateProfileData`, and that's the last thing that remains there in leveldb.

Now debugging why that happens...

**Comment by staltz** [comment]
Nothing seems wrong with the order of offset and seq of self-assigned abouts of `@QlCT...` on my phone, see:

```
88401 172
88818 173
101175 198
1541622 2666
123419498 170755
166547364 224141
230597921 302560
233317137 305825
493658130 665364
495276497 667360
499962472 672946
500292605 673340
500741026 673900
501120338 674390
506345374 680685
506749667 681172
615346583 829896
768871179 1017246
768914175 1017338
770667917 1020802
778513582 1033434
```

**Comment by arj03** [comment]
So strange. I looked at the indexing code earlier today and couldn't see why it should shuffle things around.

**Comment by staltz** [comment]
Now, for some truly revealing data:

```
offset msg.value.timestamp msg.timestamp msg.value.sequence
88401 1479734785596 1611254659473 1
88818 1479734809446 1611254659475 2
101175 1480683300719 1611254659592 14
1541622 1489663902644 1611254689461.001 205
123419498 1510163155665 1611256585312 1428
166547364 1518424161068 1611256744332 2079
230597921 1530781055994 1611257059133 3283
233317137 1531210967608 1611257073532 3334
493658130 1552943300062 1611259896845 5584
495276497 1553159354273 1611259914019 5633
499962472 1555173209941 1611259960395 5787
500292605 1555355455792 1611259963921.001 5798
500741026 1555686507554 1611259968432 5814
501120338 1556008085698 1611259972065.001 5828
506345374 1559221950071 1611260029609 6049
506749667 1559732012434 1611260036243 6083
615346583 1610392213581 1611268100582 7945
768871179 1479734785596 1614367550899 1
768914175 1479734809446 1614367551031 2
770667917 1480683300719 1614367555391 14
778513582 1489663902644 1614367569301 205
```

**Comment by staltz** [comment]
Those mean that those are in the log. Offset 1541622 in the log is the msg `%a8+ng15...` and offset 778513582 is also `%a8+ng15...`. Did we mess up with migrate? :cold_sweat:

**Comment by staltz** [comment]
Okay, I deleted db2 folder and did a full re-migrate and re-sync of db2, and this time I got the correct profile picture for `@QlCT...`, but actually I got the wrong `description`. This was the order of offsets and seqs:

```
88401 172
88818 173
101175 198
1541622 2666
123419498 170755
166547364 224141
230597921 302560
233317137 305825
493658130 665364
495276497 667360
499962472 672946
500292605 673340
500741026 673900
501120338 674390
506345374 680685
506749667 681172
615346583 829896
776698323 1030483
779341322 1035270
779750491 1036056
783338037 1041800
795425653 1058501
```

Notice that it's the same as before *up until* 615346583, then it's not the same.

The app stayed up the whole time (there were no restarts), so I believe (with 90% confidence) that it wasn't migrate's `findMigratedOffset`'s fault.

Maybe I should tell what happens, this could be valuable:

1. Manyverse starts up, and migration begins (notice the old log is approx 1 month behind the community)
1. Migration completes, but DB2 and JITDB indexes are busy indexing
1. Indexing completes, content shows on the feed
1. ssb-conn starts
1. We connect to some peers, who will start sending us quite a lot of msgs
1. Those msgs also get indexed

Is it possible that EBT and replicate will ask for data that it already has? Could it be some kind of race condition between EBT indexes finishing, and EBT "logic" kicking in?

**Comment by arj03** [comment]
Right this message: https://github.com/ssb-ngi-pointer/ssb-db2/issues/207#issuecomment-789106027 seems to indicate that it is not a problem with replicate but rather that you got some of the messages again because as you say it seems that EBT kicked in before things were correctly loaded. It seems like on the second run you got 5 of the about messages instead of 4 in the first run, which is probably why description is wrong. I'll try to answer how we can avoid this problem now. Just wanted to write this first.

**Comment by arj03** [comment]
Meanwhile can you confirm that the latest about message is actually the 5th about message of your main profile?

**Comment by arj03** [comment]
First of all the validate should have made this scenario impossible. So for some reason it did not load the state correctly like it does on [startup](https://github.com/ssb-ngi-pointer/ssb-db2/blob/d62d5ef7b412c5deaa7b7683946e8a7bdf1d7d90/db.js#L73). This seems to be because migrate is just writing directly to the [new log](https://github.com/ssb-ngi-pointer/ssb-db2/blob/2b30301f5e879413164427524d322969140b4e12/migrate.js#L260) and this is why state in db.js is not properly in sync with the data in the database. That might not be a problem in itself, but before doing anything that can add messages to the database the base index needs to complete and [this](https://github.com/ssb-ngi-pointer/ssb-db2/blob/2b30301f5e879413164427524d322969140b4e12/db.js#L73) must run.

**Comment by arj03** [comment]
This same [getAllLatest](https://github.com/ssb-ngi-pointer/ssb-db2/blob/2b30301f5e879413164427524d322969140b4e12/compat/ebt.js#L10) is also used in EBT in the [init](https://github.com/ssbc/ssb-ebt/blob/6bd6679ed71e191c11fa86a3c04b1850c5cf4dd6/index.js#L79) method so that is why it is empty.

**Comment by arj03** [comment]
I would feel a lot safer if we could simply restart db after migrate and base index has finished to make sure all the states are correctly loaded.

**Comment by staltz** [comment]
Starting to make sense! I'll continue working on this tomorrow

**Comment by staltz** [comment]
Answering [this question](https://github.com/ssb-ngi-pointer/ssb-db2/issues/207#issuecomment-789162857):

```
offset seq msg.key
88401 172 %wSXIbl2
88818 173 %cP618jV
101175 198 %8Fkg9mU
1541622 2666 %a8+ng15
123419498 170755 %P9AbSS+
166547364 224141 %3U6NfM5
230597921 302560 %IxPMh6J
233317137 305825 %qIE+ATS
493658130 665364 %lxjw/Dv
495276497 667360 %81pPqu2
499962472 672946 %fnB3cof
500292605 673340 %mdN6PUd
500741026 673900 %zNYlJ1c
501120338 674390 %iKoSdrr
506345374 680685 %02os4WG
506749667 681172 %FdQ/5RB
615346583 829896 %+7LkGeZ
776698323 1030483 %wSXIbl2
779341322 1035270 %cP618jV
779750491 1036056 %8Fkg9mU
783338037 1041800 %a8+ng15
795425653 1058501 %P9AbSS+
```
