### ISSUE TITLE
JavaScript heap out of memory, crashes

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#210]
See `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

| screenshot 1 | screenshot 2 |
|----|----|
| ![photo_2021-03-05_12-58-03](https://user-images.githubusercontent.com/90512/110106554-7d9ca280-7db2-11eb-9699-096e33fb51aa.jpg) | ![photo_2021-03-05_12-58-07](https://user-images.githubusercontent.com/90512/110106562-81302980-7db2-11eb-8333-f3e205ffd4e1.jpg) |

**Comment by arj03** [comment]
What was going on before the crash?

**Comment by staltz** [comment]
Replicating everything from scratch, and indexing simultaneously. I don't think there was any migrate going on, because there's no flume log.

**Comment by staltz** [comment]
> Replicating everything from scratch, and indexing simultaneously.

I recently did this again on my Manyverse phone account in production, and this crash happened again. Just to confirm it's still a thing. Maybe replicate+migrate+index simultaneously takes a lot of memory and we should find a way to free memory earlier.

**Comment by arj03** [comment]
Can this be closed?
