### ISSUE TITLE
Publish doesn't encrypt messages by default

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#211]
Memo raised the issue here (%u0MgEX7mwPmJHcikBBOchPHIy0lkyfPS/7C/cM6YxwU=.sha256) that the function publish in db2 works differently than db1 for private messages in that it expects the message to already be [encrypted](https://github.com/ssb-ngi-pointer/ssb-db2/blob/c0d78cfe910d520f685a7eceb602bbf566a59220/test/base-index.js#L98).

Some possible remedies:
 - Auto encrypt messages if recps is set
 - Document that publish expects a private message to already be encrypted and fail if it contains recps

**Comment by mixmix** [comment]
From app dev experience please keep auto encrypt if recps present. Forcing everyone to learn the private group and envelope spec would make it too hard
