### ISSUE TITLE
Memory leak somewhere

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#214]
@arj03 I did a `git bisect` and running `npm run benchmark` to see when did the memory consumption bump upwards, and it was this: https://github.com/ssb-ngi-pointer/ssb-db2/commit/ecdea5e48e148b7e05a4ae96c70446e0097668b0

What confuses me is how could that commit possibly use much more memory...

**Comment by mixmix** [comment]
Hope many set Interval are being called there. Could that be being  hammered?

**Comment by staltz** [comment]
See PR #215.

I might create another PR / issue about another mysterious memory leak
