### ISSUE TITLE
Too hot binding

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#292]
I was testing too hot in async to see if I can see anything, I noticed that there appears to be a missing bind on this line: https://github.com/ssb-ngi-pointer/ssb-db2/blob/62e80f09d5e00d2039f8b1aec6a6005e618e0317/log.js#L83 It should be `o.write.bind(o)`, right?

**Comment by staltz** [comment]
Hmm, technically, yes.

`o` is a sink, and there are cases where the sink uses `this` https://github.com/push-stream/push-stream/blob/master/sinks/drain.js but there are also cases of a this-less sink such as https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L641

**Comment by arj03** [comment]
Yeah, the [one](https://github.com/ssb-ngi-pointer/async-append-only-log/blob/abbd1887d3ef414d1c1f67f49c70244c50298ebb/test/stress-test.js#L48) used in async log tests used this :)

**Comment by staltz** [comment]
Let's slap a `bind` on it then :100:
