### ISSUE TITLE
Private groups

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#3]
Plan:
 - [x] add decryptor module that sits between log and views and keeps track of which messages can be decrypted and which ones are private
 - [x] make small wrapper around atomically for browser support
 - [x] add tests for private (indexes, get)
 - [x] Add EBT test
 - [x] be 100% that anything exposed on the network will not leak private messages. Test createHistoryStream & EBT. 
 - [x] Test [isPrivate](https://github.com/ssb-ngi-pointer/ssb-db2/blob/master/operators/index.js#L52)
 - [ ] extend ssb-fixtures with private groups https://github.com/ssb-ngi-pointer/ssb-fixtures/issues/1
 - [ ] add ability to decrypt private groups. This means extending the decryptor module to know about new keys and to be able to pass old messages that can now be decrypted to indexes. This is the hardest part because of concurrency of keys and log messages coming in. One option would be to simply pause the ordinary log while a new key is added. We need to figure out exactly how fast this is. The idea is to have a key store with a key + bit saying if the indexes know of the messages from this key or not. Because the indexes are not reduce, it doesn't matter if we crash in the middle and do some indexes multiple times.

**Comment by arj03** [comment]
Been thinking about this. 

I think we need to store message encrypted as ssb-db. Then a crypto store that sits between the flumelog and views, including jitdb. It would have an 2 bitmap indexes: encrypted messages and messages we can decrypt.

On stream it would use the can decrypt index to only decrypt messages needed. This should be very efficient.

When added a new group to key to store it would run through the messages in can't decrypt yet (diff between the bitmaps) and update the "can decrypt" bitmap. The messages that can be decrypted this way would be given to the views. They would then either just update their indexes (in jitdb, base and social indexes this should be really fast (<1s)) or do a full reindex for reduce style. We need to consider this for about & contacts.

**Comment by staltz** [comment]
Great idea to use bit vectors like this! In general I'm favorable of using bitvectors as a way of decreasing the search space for subsequent indexes.

**Comment by arj03** [comment]
Thanks. I'm hoping that @mixmix might be interested in pairing on this as he has a lot of experience in this area already.

**Comment by mixmix** [comment]
This sounds great. Originally I thought that we would want to reindex a smaller subset : encrypted + can't yet decrypt + author.

This is because with ssb-tribes we keep track of who we know is in a group to reduce the number of group keys we have to try. Do with reindexing we could take advantage of that. One problem with that though is that as you decrypt a group you will discover new members of the group... So question is whether multiple passes make sense or just one complete pass (probably the latter).

Re pairing - yes really interested in that @arj03 ! Ping me on signal to figure out when / how?

**Comment by mixmix** [comment]
One thing I notice is that with ssb-db we added a generic #reindex method.
I think we don't need that here, and instead want a #updateWithKey (ie please update all your states given this new decryption key)

**Comment by arj03** [comment]
More notes from the call with mix relevant to this task: chunk decode messages.

Also worker threads like https://github.com/hyperdivision/fast-async-zlib for decryption
