### ISSUE TITLE
Error during migration and encoding Integer to BIPF

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#300]
I got this bug report to Manyverse, technical details are:

- Manyverse for Windows: 0.2201.5
- ssb-db2: 2.8.5 
- jitdb: 4.0.1
- bipf: 1.5.4
- async-append-only-log: 3.1.1

The person who reported described it as: "Exception during .ssb import."

![image](https://user-images.githubusercontent.com/90512/148370420-8f927be5-0d73-48c2-8058-45eb8d9348b8.png)

Interpreting the error above, apparently it was encoding some objects (supposedly reading the JSON from `flumelog.offset` and converting it to BIPF for `log.bipf`) and it stumbled upon an integer that bad inputs on this line of code:

https://github.com/ssbc/bipf/blob/3e113ae5531a5e1c4bba4098e549342ace2ed7e6/index.js#L28

Would be very useful to know what the JSON record actually was there, but :shrug:

**Comment by arj03** [comment]
Hmm seems like it's an unsigned int. This [line](https://github.com/ssbc/bipf/blob/3e113ae5531a5e1c4bba4098e549342ace2ed7e6/index.js#L149) seems to check for unsigned. So seems to be a bug in bipf?

**Comment by staltz** [comment]
Spot on! Thanks

**Comment by staltz** [comment]
I updated Manyverse with bipf 1.5.5, and anyway this was never an ssb-db2 issue, so I'll close.
