### ISSUE TITLE
Questions about db2 and db

### ISSUE THREAD

**Issue by Scott20222** [ssb-ngi-pointer/ssb-db2#309]
Hello,Anders.I have a question about the db2. Have we not upgraded our current go-pub and nodejs pub to db2? I use manyverse to access both pubs, either I cannot get the follow data of pub or crash. Is it normal for you to use manyverse to access pub? The last pub invite you sent (between-two-worlds.dk:8008:@lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=.ed25519~WeOCKPS5lYefmHI8MzojbCHvBvt6MpC9v/scID0sVKU=
) I was rejected, is it not because of the limit of the number of times, can you send another one?thanks a lot.

**Comment by arj03** [comment]
This must be related to this issue? https://gitlab.com/staltz/manyverse/-/issues/1633. Sadly I shut down the pub recently, so invites are not working there anymore. The connections and invites should not be connected to db2 in any way. One could / (should :)) make a new pub project that uses db2 but that is a different story and not really related to the issue with connecting.

**Comment by Scott20222** [comment]
Thank you very much for your reply, would you like to make a new pub project that uses db2? We can provide financial support. If pub cannot interact with the manyverse on the mobile side, it will be completely replaced by room. I think pub and room should coexist. Hope to get your feedback, thank you.
