### ISSUE TITLE
Plan to use db2 in Manyverse

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#31]
## What Manyverse currently depends on

Regarding this version https://github.com/staltz/manyverse/commit/6902430a69021f8a960c3e78fdc046360fe73a89
    
### Bottom-up order

Tick these boxes when we have a solution in ssb-db2 for them:

- [x] **ssb-db** `ssb.publish()`
  - Obviously
- [x] **ssb-db** `ssb.progress()`
  - ~~Used in Manyverse / backend / plugins / syncing~~
  - ~~Used in `ssb-ebt` (but it's optional, not required!)~~
- [x] **ssb-db** `ssb.get`
  - ~~Used in Manyverse / backend / plugins / friendsUtils~~
  - ~~Used in ssb-threads~~
  - ~~Used in `ssb-about`~~
- [x] **ssb-db** `ssb.createWriteStream`
  - Used by `ssb-replicate`
- [x] **ssb-db** `ssb.messagesByType` (**flumeview-level**, indexes / links)
  - ~~Used in `ssb-conn` scheduler for looking up msgs of type `"pub"`~~
- [x] **ssb-db** `ssb.links` (**flumeview-level**, indexes / links)
  - ~~Used in Manyverse / backend / plugins / friendsUtils~~ using ssb-db2 now
- [x] **ssb-db** `ssb.createLogStream()` (**flumeview-level**, indexes / time)
  - Used by (legacy) `ssb-replicate`
    - Used in Manyverse (alongside `ssb-ebt`)
  - ~~Used by `ssb-suggest`~~
  - ~~Used in Manyverse / backend / plugins / syncing for tracking replication progress~~
  - ~~Used by `ssb-threads` in Manyverse to get a UI counter of public updates coming in~~
- [x] **ssb-db** `ssb.createFeedStream()` (**flumeview-level**, indexes / feed)
  - Not used anymore, replaced with `ssb.createLogStream`
- [x] **ssb-db** `ssb.createUserStream()` (**flumeview-level**, indexes / clock)
  - This is based on the same index that `ssb.createHistoryStream()` uses, so maybe we cannot remove this index
  - ~~Used in Manyverse to get the hops=0 author's own `post` msgs to skip those in a UI counter of new content~~
- [x] **ssb-backlinks@1.0.0** (**flumeview-links**)
  - ~~Used by `ssb-suggest`~~
  - ~~Used in `ssb-about`~~
  - ~~Used in Manyverse for likes/reactions~~
  - ~~Used by `ssb-blobs-purge`~~
  - ~~Used by `ssb-threads` (see below)~~
- [x] **ssb-friends** (**flumeview-reduce**)
  - Used in Manyverse to whether someone follows or is followed by the hops=0 author
  - Used by `ssb-conn`
  - Used by `ssb-suggest`
- [x] **ssb-threads** (**flumeview-level**)
  - Used in Manyverse for threads, this is important
- [x] **ssb-private** (**flumeview-links**)
  - ~~Used by `ssb-threads`~~
    - Used in Manyverse for private threads
- [x] **ssb-query** (**flumeview-query**)
  - Imported in Manyverse for NOTHING

### Feature-wise benchmarks in Manyverse

| Feature | Initial sync duration | Impact ¹ |
|---------|-----------------------|------------|
| Baseline     | 54.76s |  |
| A: Minus ssb-db / indexes / links | 60.95s ² |  |
| B: Minus ssb-db / indexes / time | 53.82s | ⦁ |
| C: Minus ssb-db / indexes / feed | 48.17s | ⦁⦁⦁⦁⦁⦁⦁ |
| D: Update ssb-db 19.3=>20.3 | 48.06s | ⦁⦁⦁⦁⦁⦁⦁ |
| E: Update ssb-backlinks 1.0=>2.1 | 49.25s | ⦁⦁⦁⦁⦁⦁ |
| F: Update ssb-friends 4.1=>4.3 | 58.78s | ⦁⦁⦁⦁ |
| G: Minus ssb-private | 50.36s | ⦁⦁⦁⦁ |
| H: Minus ssb-query | 49.35s | ⦁⦁⦁⦁⦁ |
| I: Remove extra flumeview-level in ssb-threads | 48.93s | ⦁⦁⦁⦁⦁⦁ |
| C + D + E + F + H + I | 50.04s | ⦁⦁⦁⦁ |
| C + H | 53.70s | ⦁ |

**Comments:**

- ¹ **Impact** means difference in seconds between this and the "All" case, where each ⦁ dot represents -1 second
- ² The fixture used in the benchmark doesn't have any message of type "pub" and it doesn't open any profile screen (hence not using backend/plugins/friendsUtils), so maybe this explains why it didn't get slower by removing indexes/links

### Conclusions

Before using ssb-db2 in Manyverse, we could:

- [x] Replace `ssb.createFeedStream()` with `ssb.createLogStream()`
  - Replace in ssb-threads
  - Replace in Manyverse / backend / plugins / syncing
  - Replace in Manyverse / frontend / ssb / plugins / threadsUtils / publicRawFeed
  - Hard-disable `ssb.createFeedStream()` by replacing in noderify the file `ssb-db/indexes/feed`
- [x] Remove extra flumeview-level in ssb-threads
- [x] Remove ssb-query
- [x] Update ssb-friends to 4.3
- [x] Update ssb-backlinks to 2.1
- [x] Update ssb-db to 20.3
  - Check first drawbacks of 20.3 (see what cel posted)
- [x] Replace `ssb.messagesByType` and `ssb.links` with another log
  - Replace it in Manyverse / backend / plugins / friendsUtils
  - Replace it in ssb-conn, using `pull-drain-gently` because fetching "pub" messages is not UI priority
  - Hard-disable `links` index in `ssb-db`

### Final bits

- [x] JITDB: save JIT indexes every 60s
- [x] Bring ssb-suggest back
- [x] db2: dangerouslyKillFlumeWhenMigrated and careful tests

**Comment by arj03** [comment]
Currently in testing. Probably not ready for review yet.

- ssb-about is an empty shell for [ssb-social-index](https://github.com/ssbc/ssb-social-index/pull/4)
- ssb-suggest [PR](https://github.com/ssbc/ssb-suggest/pull/9)

**Comment by arj03** [comment]
Seems like with these 2 PRs and a change to blobs-purge backlinks can be removed? That would be quite huge for initial indexing.

**Comment by staltz** [comment]
> Seems like with these 2 PRs and a change to blobs-purge backlinks can be removed? That would be quite huge for initial indexing.

Yes!

**Comment by arj03** [comment]
This is now 20/20! Nice :)

**Comment by staltz** [comment]
Yes! It's not all confirmed yet, but at least all the work in `ssb-*` modules is done, there's only work remaining in Manyverse and its testing

**Comment by staltz** [comment]
Here are all the muxrpc APIs the frontend JS in Manyverse calls upon app startup:

```
async settingsUtils,read([])
async whoami([])
async aboutSelf,get([{"id":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","image":true}])
async aboutSelf,get([{"id":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","image":true}])
source aboutSelf,stream([{"id":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","field":"name"}])
source aboutSelf,stream([{"id":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","field":"image"}])
source aboutSelf,stream([{"id":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","field":"description"}])
async friends,isFollowing([{"source":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","dest":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519"}])
async friends,isBlocking([{"source":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","dest":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519"}])
async friends,isFollowing([{"source":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","dest":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519"}])
async friends,isBlocking([{"source":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","dest":"@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519"}])
source syncing,migrating([])
source syncing,indexing([])
source threads,publicUpdates([{"allowlist":["post","contact"]}])
source threads,privateUpdates([{"allowlist":["post"],"includeSelf":true}])
source conn,peers([])
source bluetooth,bluetoothScanState([])
source conn,stagedPeers([])
source dhtInvite,hostingInvites([])
source threads,publicSummary([{"allowlist":["post","contact"]}])
source threads,private([{"threadMaxSize":1,"allowlist":["post"]}])
```

**Comment by staltz** [comment]
## Steps to reproduce slowness

### Clone repo

```
git clone https://gitlab.com/staltz/manyverse.git
```

### Go to `db2-more` branch

```
git checkout db2-more
```

### Setup tools

#### Use Node 10 or Node 12

This is important because I think it should give you prebuilds of some Rust node modules. Otherwise you'll have to setup Rust (not too hard, it's just https://rustup.rs/)

#### `npm install`

This will install generally-needed packages.

### Build and run

#### `npm run build-desktop`

This will build **both** frontend JS and backend JS. Will install backend packages, compile backend nodejs native modules (C or Rust), compile TS to JS, webpack the Electron UI.

#### `npm run desktop`

This will run the Electron app. Note it will run on your `~/.ssb` folder, *will delete* (in case it existed) and then create `~/.ssb/db2` and begin migrating.

### Development cycle

#### Developing the backend JS

- Edit `src/backend/loader.desktop.ts` to tweak general "startup" of the backend, such as defining the `DEBUG` env var
- Edit `src/backend/ssb.ts` to configure sbot
- Edit `src/backend/plugins/*` to change custom secret-stack plugins (such as aboutSelf)

If files in that folder are changed, you'll have to do `npm run build-desktop`

#### Developing the frontend JS

- Edit `src/desktop/index.ts` to change how the frontend muxrpc client behaves, currently it only does this:

```js
ssb.whoami((err, {id}) => {
  console.log('whoami', id);
});

ssb.db2migrate.start();

pull(
  ssb.threadsUtils.publicFeed({}),
  pull.take(3),
  pull.drain((thread) => {
    console.log(thread);
  }),
);
```

Once any files in `src/desktop/*` are changed, **it's enough to do** `npm run build-frontend` (which will skip building the heavy-weight backend), and then `npm run desktop`.

**Comment by staltz** [comment]
### More weirdness

I removed ssb-suggest, alright. But I still experience some weirdness.

With the frontend doing `pull(ssb.threadsUtils.publicFeed({}), pull.take(3),...`, the backend JS (ssb-threads) SHOULD fetch just 3 thread summaries, because it should do only 3 "pulls" of values, but in reality it fetches **6 thread summaries** but the frontend somehow gets only 3, the even ones, and the odds are dropped.

But if I change that line to `pull(ssb.threadsUtils.publicFeed({maxThreads:3}), pull.take(3),...`, then the backend JS fetches *infinite* thread summaries! And doesn't actually respond to the frontend.

**Comment by staltz** [comment]
**DISCOVERED THE CULPRIT:** pull-weird in muxrpc doesn't allow us to "pull a `source` one item at a time", instead, it dumps all the items to the sink as fast as it can, with no backpressure other than "end/err". This is expressed in `ssb.threads.publicSummary` which keeps on spamming the about fetching.

Solution will probably be to convert `ssb.threads.publicSummary` from `source` to `async` somehow, so the frontend can control the intake of thread summaries.

**Comment by staltz** [comment]
@arj03 I put ssb-suggest back in. It didn't slow things down by much, overall. We can someday make an optimized ssb-suggest alternative.

**Comment by staltz** [comment]
Can you believe it?
