### ISSUE TITLE
canDecrypt and encrypted are recognized as jitdb indexes

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#333]
When you call `jitdb.reindex`, it causes all lazy indexes to be loaded, and this causes jitdb to "load" `canDecrypt` and `encrypted` as jitdb indexes, even though they are not, and that's because jitdb looks into the `db2` folder and loads any file that ends with `.index`.

A proposed fix would be to make a folder `db2/jitdb` where jitdb can do whatever it wants, and thus put `canDecrypt` and `encrypted` outside of that so that jitdb doesn't mess with it.

@arj03 If you agree, I'll work on this. It's a breaking change, but gladly doesn't cause indexes to be rebuilt. Just have to apply a one-time fix to move the files around.

**Comment by arj03** [comment]
Sounds good
