### ISSUE TITLE
Try chainedBatch in leveldb to avoid JS objects when batching

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#50]
See https://github.com/Level/level#dbbatch-chained-form and https://github.com/Level/leveldown#chainedbatch, I think it works like this:

```js
let batch = level.batch()

// later

batch = batch.put([root, 'r', shortKey], processed)
            
// later

batch = batch.put([root, 'r', shortKey], processed)

// later

batch.write({ keyEncoding: jsonCodec }, cb)
batch = level.batch()
```

cc @arj03

**Comment by arj03** [comment]
Oh that, we are batch writing already

**Comment by staltz** [comment]
Major problem with this idea is this bit that the docs mention:

> options.keyEncoding and options.valueEncoding are not supported here.

**Comment by arj03** [comment]
Oh :(
