### ISSUE TITLE
Decrypt less often?

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#62]
![Screenshot from 2020-12-09 00-28-49](https://user-images.githubusercontent.com/90512/101548990-89481b00-39b5-11eb-842e-b8de4c9f1afd.png)

@arj03 Using the Chrome profiler I noticed that all records from `log.stream` get an attempted decrypt using the new private index. This goes all the way down to sodium for every record. Could we use some simple heuristics to prevent some of those, e.g. could we check if the `content` is an object or a string (does BIPF let us know which one is it?) or could we check whether `content` ends with ".box" / ".box2"?

**Comment by arj03** [comment]
It should only try to decrypt if [content is a string](https://github.com/ssb-ngi-pointer/ssb-db2/blob/master/indexes/private.js#L116). In the branch with group support there is also a box1 check.

**Comment by arj03** [comment]
I think this one can be closed
