### ISSUE TITLE
rename `base` index to `ebt`

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#74]
"Base index" used to do more, but nowadays seems mostly used for EBT concerns, so it could be renamed to "EBT Index".

Also, because it's not critical for displaying content, maybe `onDrain` doesn't need to strictly wait for `base` anymore.

That said, base index is used for validate as well. See db.js:

https://github.com/ssb-ngi-pointer/ssb-db2/blob/da848345e281bc187cdabf2df3632b07bfcd01d0/db.js#L43-L54

Question @arj03: so this means we cannot rename base to EBT, and we have to make `onDrain` wait for base? What if split it, one index for getLatest (the new "base", which is strictly needed), and one index for `getMessageFromAuthorSequence` (the new "ebt" index, needed only if you have EBT)?

Another side question: doesn't `publish` need to strictly wait for `getLatest` to load up? Similar to `onIndexesStateLoaded`.

Often, it will make sense to have EBT installed, but since this is the new ssb DB, I can also imagine use cases where developers want strictly-offline usage, so they wouldn't include the EBT index (neither the compat file) because they only want to do local queries and want to optimize the performance of those queries.

**Comment by arj03** [comment]
Right. 

So yeah leave latest in base and move the author thing to a EBT index. Would be nice with some numbers, but now with index sharing this shouldn't make a bit overhead.

Publish: yes

You can remove [getSync](https://github.com/ssb-ngi-pointer/ssb-db2/blob/da848345e281bc187cdabf2df3632b07bfcd01d0/db.js#L359)

**Comment by staltz** [comment]
Thanks! I was looking at getSync right now thinking "what's this doing here". Will probably address that when I do implicit onDrain for all read APIs

**Comment by staltz** [comment]
I'll also run benchmarks for the two indexes separate versus together, just to know what kind of impact that has.
