### ISSUE TITLE
We need progress() API on the db plugin

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#88]
Similar to https://github.com/ssbc/ssb-db/blob/788cd5c5d067b3bc90949337d8387ba1b0151276/db.js#L7

**Comment by arj03** [comment]
There is: https://github.com/ssb-ngi-pointer/ssb-db2/blob/master/db.js#L225, bu

**Comment by staltz** [comment]
Ok! I'll try to use that and open another issue if I find an issue
