### ISSUE TITLE
Migrate takes a long time before copying messages

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#95]
I just debugged here on my Manyverse why is there a multi-second delay between pressing 'like' and seeing the like appear (multi-second means more than 20 seconds). It seems logical that the `vote` is published on the old log, but db2-migrate has to move that to the new log before allowing db2 queries to succeed.

Turns out that the initial `scanAndCount` inside db2 migrate takes 31 seconds to complete. I think there's two bad ideas going on:

- `scanAndCount` scans through the *entire* new log just to count how many records it has (`msgCountNewLog`)
- After that, the *entire* old log is scanned, but its first `msgCountNewLog` messages are dropped due to the use of a `skip` pull-stream operator

I think we need a way of setting the cursor on the old log directly. I'm thinking that we need to save the offset on the old log where we know we have migrated to the new log. Maybe we need to save this tiny piece of information (let's call it `migratedOffset`) in a separate file? It would also be good to have some protection and sanity checks against overriding or duplicating messages on the new log in case `migratedOffset` happens to refer to be out of sync with the actual migration status (this could happen e.g. if the new log is saved and a crash happens right before `migratedOffset` is saved, whereas in the default case they should be saved "at the same time").

Thoughts @arj03 ?

**Comment by arj03** [comment]
Yeah this is a bit of a state nightmare. Especially because you really don't want to add the same message twice and adding a add guard that checks if the message is already there is way to slow.

What if instead of tried finding the last message in the new log first. It should be possible to start close to the end and get the last one. After finding that, you should be able to get the seq (in old flume terminology ;-)) of that in the old log. Then it should be a matter of stream from there?

**Comment by staltz** [comment]
Yeah you're right about the state nightmare, I'll try your suggestion. :)

**Comment by staltz** [comment]
Help me out a bit? Given a msg key, how do I retrieve its (byte) offset position in the old log? Or even better, with ssb-db(1) APIs, since that might be the only interface I have with the old log. I can't quite find an API for this in ssb-db.

**Comment by arj03** [comment]
It should be using the [key index](https://github.com/ssbc/ssb-db/blob/2162df147d513e774f2fb3d582ff8055558a31e7/create.js#L69).

**Comment by staltz** [comment]
Do you know a way of accessing that from the public API? They don't seem to be exported

**Comment by staltz** [comment]
I have an idea. It's semi-hacky, you'll see
